# Generated by Django 3.2.9 on 2021-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=55, null=True),
        ),
    ]
